{% set version = "0.0.1" %}


package:
  name: exui
  version: {{ version }}

source:
  # No tags...hurray
  url: https://github.com/turboderp/exui/archive/refs/main.tar.gz
  sha256: 9f90f8f4edfb7092b416faac30b0a234c10bb4246b52b867e41ec64f084a91cc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - pytorch >=2.1.0
    - pynvml
    - exllamav2 >=0.0.10
    - flask >=2.3.2
    - waitress >=2.1.2
  run:
    - python >=3.8
    - pytorch >=2.1.0
    - pynvml
    - exllamav2 >=0.0.10
    - flask >=2.3.2
    - waitress >=2.1.2

# test:
#   imports:
#     - n/a
#   commands:
#     - pip check
#   requires:
#     - pip

about:
  home: https://github.com/turboderp/exui
  license: MIT
  license_file:
    - LICENSE
  summary: This is a simple, lightweight browser-based UI for running local inference using ExLlamaV2.
  doc_url: https://github.com/turboderp/exui

extra:
  recipe-maintainers:
    - mediocretech
